# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: fail2ban_exporter
before:
  hooks:
    - make go/dependencies
builds:
  -
    binary: fail2ban_exporter
    dir: src
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  -
    wrap_in_directory: true
    files:
    - LICENSE
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
