style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/hectorjsmith/fail2ban-prometheus-exporter
options:
  commit_groups:
    title_maps:
      feat: Added
      fix: Fixed
      revert: Reverted
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
      - Changed
      - Deprecated
      - Removed
      - Security
